CREATE DATABASE DataBase;

CREATE SCHEMA DataBase;
USE DataBase;

CREATE TABLE Messwerte(
    ID INTEGER PRIMARY KEY,
    Sensoren-ID INTEGER NOT NULL,
    Messwert VARCHAR(20) NOT NULL,
    Zeitstempel TIMESTAMP NOT NULL,
    FOREIGN KEY (Sensoren-ID) REFERENCES Sensoren(ID)
);

CREATE TABLE Sensoren(
    ID INTEGER PRIMARY KEY,
    Datenstation-ID INTEGER NOT NULL,
    Typ-ID INTEGER NOT NULL,
    FOREIGN KEY (Datenstation-ID) REFERENCES Datenstationen(ID),
    FOREIGN KEY Typ-ID REFERENCES Sensortyp(ID)
);

CREATE TABLE Sensortyp(
    ID PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    Einheit VARCHAR(20) NOT NULL
);

CREATE TABLE Datenstationen(
    ID PRIMARY KEY,
    Standort VARCHAR(20) NOT NULL
);
